name: CI

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1.3
          release_name: v0.1.3
          body: asdf
      - name: Print release upload URL
        uses: actions/github-script@v3
        with:
          script: |
            const uploadUrl = '${{ steps.create_release.outputs.release_upload_url }}';
            console.log({ uploadUrl, uploadUrlReversed: [...uploadUrl].reverse().join('') });
            return true;
