name: CI

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1.2
          release_name: v0.1.2
          body: asdf
      - name: Print release upload URL
        run: echo Upload URL = ${{ steps.create_release.outputs.release_upload_url }}
