name: CI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Publish to npm
        id: publish
        run: |
          set -e
          echo '---
          "@jakzo/testpkg": patch
          ---

          testing' > .changeset/thirty-toys-provide.md
          echo 'registry = "https://registry.npmjs.org"' > .npmrc
          yarn install --frozen-lockfile
          yarn changeset version
          yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_authToken: ${{ secrets.NPM_TOKEN }}
